version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
      - DATABASE_URI=sqlite:///data/price_monitor.db
      - SECRET_KEY=${SECRET_KEY:-change_this_to_a_random_secure_string}
      - SCHEDULER_INTERVAL_MINUTES=${SCHEDULER_INTERVAL_MINUTES:-1440}
    restart: unless-stopped
