services:
  # A web service for the Flask application
  - type: web
    name: price-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: SECRET_KEY
        generateValue: true
      - key: API_KEY
        generateValue: true
      - key: RENDER
        value: true
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DATABASE_URL
        fromDatabase:
          name: price-tracker-db
          property: connectionString

  # A cron job for updating prices
  - type: cron
    name: price-tracker-updater
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -c "from tasks import update_all_prices; from app import app; update_all_prices(app)"
    plan: free
    schedule: "0 0 * * *"  # Run daily at midnight
    envVars:
      - key: FLASK_ENV
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: SECRET_KEY
        fromService:
          name: price-tracker
          type: web
          envVarKey: SECRET_KEY
      - key: API_KEY
        fromService:
          name: price-tracker
          type: web
          envVarKey: API_KEY
      - key: RENDER
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: price-tracker-db
          property: connectionString

databases:
  - name: price-tracker-db
    plan: free
    databaseName: price_tracker
    user: price_tracker_user
